{% set name = "bumpversion" %}
{% set version = "0.6.0" %}
{% set hash = "4ba55e4080d373f80177b4dabef146c07ce73c7d1377aabf9d3c3ae1f94584a6" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/b/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  entry_points:
    - bumpversion = bumpversion:main
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - bumpversion

  commands:
    - bumpversion --help  # [not win]

    # 'bumpversion --help' is broken on Windows:
    # https://github.com/peritus/bumpversion/issues/154
    - where bumpversion  # [win]

about:
  home: https://github.com/peritus/bumpversion
  license: MIT
  license_file: LICENSE.rst
  summary: Version-bump your software with a single command!
  license_family: MIT

extra:
  recipe-maintainers:
    - nicoddemus
