{% set name = "bumpversion" %}
{% set version = "0.5.3" %}
{% set hash = "6744c873dd7aafc24453d8b6a1a0d6d109faf63cd0cd19cb78fd46e74932c77e" %}
package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/b/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  entry_points:
    - bumpversion = bumpversion:main
  number: 1002
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vvv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - bumpversion

  commands:
    - bumpversion --help  # [not win]

    # 'bumpversion --help' is broken on Windows:
    # https://github.com/peritus/bumpversion/issues/154
    - where bumpversion  # [win]

about:
  home: https://github.com/peritus/bumpversion
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  summary: 'Version-bump your software with a single command!'  

extra:
  recipe-maintainers:
    - nicoddemus
