appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Pb6bZ7sNHOofkI2MkkKnPV0WT65fyH2wND3XXCki2pF+Y9n9V7yJXpREARtVnr0fjz9VjA/gfxdQwCb147878JAtNvIaRFvaU1ldpitHFikISODFjUkeWEWAKDJ60bU5bUNZmSKMgRhQZBWq3X1w4ahQaFHEGUrXEHICm9pqabJ++XLCXMhRNyZ7ScxuNSWIIn0owprbeaBJOvVojTIaOMVqX79pXMYnIb4DK8G6AAwmtwQvVRsqMYcVzA3LNJPZWU6bizAeW4BwC/Igy/AGD/+KOIfF42VN3IQh8v9p+4Fb35gYMSBQEnN9Absj+nBsvy5K47nKfbbmYO5yoe3xocHe8zuH1xoTMThxMd4NuV2ZLiNx0SOCleznBhSTctj+fx3398O4pAARzu7tbmfG8GdhtVszQqs04ZqIGL19SamMn6uM+gI+NPwHyWjgU2BP86N00JcQah+JJjFsSj1n+rntkcVDMoZBe9GTrITuAx5fcc6yeZOdpqTfTgGas2MiV7GuJL4lEIqZIXUvwTepQmhD4vRRMr+mYyPaNaqfyGfR/UesRRJ9VQQCVUeRJX5eabYugVq0K7Zk52N/y6eiXqn6QWezoxXHu43805grmEjb33B9BjjImu70YJycjAyl/x3VraSe6LXnJ19DXyI5Fhr2/IcOU9/KWBZ2FkMy8JY=}
conda_forge_output_validation: true
